// packages/vue/src/components/Modal/Modal.vue
<script lang="ts">
import { defineComponent } from 'vue';
import { modal } from '@a11yui/core';

export default defineComponent({
  name: 'A11yModal',
  props: {
    forceAction: {
      type: Boolean,
      default: false,
    }
  },
  mounted() {
    if (modal) modal.on(this.$refs.container as HTMLElement);
  },
  beforeUnmount() {
    if (modal) modal.off(this.$refs.container as HTMLElement);
  },
});
</script>

<template>
  <div
    ref="container"
    class="a11y-modal"
    :class="{ 'a11y-modal-force-action': forceAction }"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/lib/Modal/Modal.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { modal } from '@a11yui/core';
  import { createClassString } from '@shared/utils';

  let classProp: string = '';
  export { classProp as class };
  export let forceAction: boolean = false;

  let container: HTMLDivElement

  onMount(() => {
    if (container) modal.on(container);
  });

  onDestroy(() => {
    if (container ) modal.off(container);
  });
</script>

<div
  class={
    createClassString(
      'a11y-modal',
      forceAction ? 'a11y-modal-force-action' : '',
      classProp ? classProp : '',
    )
  }
  bind:this={container}
  {...$$restProps}
>
  <slot></slot>
</div>
