// packages/vue/src/components/Tabs/Tabs.vue
<script lang="ts">
import { defineComponent } from 'vue';
import { tabs } from '@a11yui/core';

export default defineComponent({
  name: 'A11yTabs',
  mounted() {
    if (tabs) tabs.on(this.$refs.container as HTMLElement);
  },
  beforeUnmount() {
    if (tabs) tabs.off(this.$refs.container as HTMLElement);
  },
});
</script>

<template>
  <div
    ref="container"
    class="a11y-tabs"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/lib/Tabs/Tabs.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { tabs } from '@a11yui/core';
  import { createClassString } from '@shared/utils';

  let classProp: string = '';
  export { classProp as class };

  let container: HTMLDivElement

  onMount(() => {
    if (container) tabs.on(container);
  });

  onDestroy(() => {
    if (container ) tabs.off(container);
  });
</script>

<div
  class={
    createClassString(
      'a11y-tabs',
      classProp ? classProp : '',
    )
  }
  bind:this={container}
  {...$$restProps}
>
  <slot></slot>
</div>
