// packages/react/src/components/Tabs/Tabs.tsx
import { forwardRef, useEffect } from 'react';
import { tabs } from '@a11yui/core';
import { createClassString } from '@shared/utils';
import { useForwardedRef } from '../../hooks';

import type {
  PolymorphicComponentPropsWithRef,
  PolymorphicRef,
} from '../../types';

import './tabs.scss';

interface Props {
  className?: string;
}

export type TabsProps<C extends React.ElementType> =
  PolymorphicComponentPropsWithRef<C, Props>;

export const Tabs = forwardRef(
  <C extends React.ElementType = 'div'>(
    { as, className, ...rest }: TabsProps<C>,
    ref?: PolymorphicRef<C>,
  ) => {
    const Component = as || 'div';

    const safeRef = useForwardedRef(ref);

    useEffect(() => {
      const containerEl = safeRef?.current;
      if (!containerEl || !tabs) return;

      tabs.on(containerEl);

      return () => {
        tabs.off(containerEl);
      };
    }, []);

    return (
      <Component
        {...rest}
        ref={safeRef}
        className={createClassString('a11y-tabs', className ? className : '')}
      />
    );
  },
);

Tabs.displayName = 'Tabs';

export default Tabs;

// packages/svelte/src/lib/Tabs/Tabs.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { tabs } from '@a11yui/core';
  import { createClassString } from '@shared/utils';

  let classProp: string = '';
  export { classProp as class };

  let container: HTMLDivElement

  onMount(() => {
    if (container) tabs.on(container);
  });

  onDestroy(() => {
    if (container ) tabs.off(container);
  });
</script>

<div
  class={
    createClassString(
      'a11y-tabs',
      classProp ? classProp : '',
    )
  }
  bind:this={container}
  {...$$restProps}
>
  <slot></slot>
</div>
