// packages/vue/src/components/Accordion/Accordion.vue
<script lang="ts">
import { defineComponent } from 'vue';
import { accordion } from '@a11yui/core';

export default defineComponent({
  name: 'A11yAccordion',
  props: {
    multiselect: {
      type: Boolean,
      default: false,
    },
  },
  mounted() {
    if (accordion) accordion.on(this.$refs.container as HTMLElement);
  },
  beforeUnmount() {
    if (accordion) accordion.off(this.$refs.container as HTMLElement);
  },
});
</script>

<template>
  <div
    ref="container"
    class="a11y-accordion"
    :aria-multiselectable="multiselect"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/lib/Accordion/Accordion.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { accordion } from '@a11yui/core';
  import { createClassString } from '@internal/utils';

  let classProp: string = '';
  export { classProp as class };
  export let multiselect: boolean = false;

  let container: HTMLDivElement

  onMount(() => {
    if (container) accordion.on(container);
  });

  onDestroy(() => {
    if (container ) accordion.off(container);
  });
</script>

<div
  class={createClassString('a11y-accordion', classProp ? classProp : '')}
  bind:this={container}
  aria-multiselectable={multiselect}
  {...$$restProps}
>
  <slot></slot>
</div>
