// packages/react/src/components/Accordion/Accordion.tsx
import { useEffect } from 'react';
import { accordion } from '@a11yui/core';
import { createClassString } from '@internal/utils';
import { useForwardedRef } from '../../hooks';

import './accordion.scss';

import { forwardRef } from 'react';

import type {
  PolymorphicComponentPropsWithRef,
  PolymorphicRef,
} from '../../types';

interface Props {
  className?: string;
  multiselect?: boolean;
}

type AccordionProps<C extends React.ElementType> =
  PolymorphicComponentPropsWithRef<C, Props>;

export const Accordion = forwardRef(
  <C extends React.ElementType = 'div'>(
    { as, className, multiselect, ...rest }: AccordionProps<C>,
    ref?: PolymorphicRef<C>,
  ) => {
    const Component = as || 'div';

    const safeRef = useForwardedRef(ref);

    useEffect(() => {
      const containerEl = safeRef?.current;
      if (!containerEl || !accordion) return;

      accordion.on(containerEl);

      return () => {
        accordion.off(containerEl);
      };
    }, []);

    return (
      <Component
        {...rest}
        ref={safeRef}
        className={createClassString(
          'a11y-accordion',
          className ? className : '',
        )}
        aria-multiselectable={multiselect}
      />
    );
  },
);

Accordion.displayName = 'Accordion';

export default Accordion;

// packages/svelte/src/lib/Accordion/Accordion.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { accordion } from '@a11yui/core';
  import { createClassString } from '@internal/utils';

  let classProp: string = '';
  export { classProp as class };
  export let multiselect: boolean = false;

  let container: HTMLDivElement

  onMount(() => {
    if (container) accordion.on(container);
  });

  onDestroy(() => {
    if (container ) accordion.off(container);
  });
</script>

<div
  class={createClassString('a11y-accordion', classProp ? classProp : '')}
  bind:this={container}
  aria-multiselectable={multiselect}
  {...$$restProps}
>
  <slot></slot>
</div>
