// packages/vue/src/components/Tabs/List/List.vue
<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'A11yTabsList',
  props: {
    vertical: {
      type: Boolean,
      default: false,
    },
  },
  data(props) {
    const orientation = props?.vertical ? 'vertical' : 'horizontal';

    return {
      orientation,
    };
  },
});
</script>

<template>
  <div class="a11y-tabs-list" :aria-orientation="orientation">
    <slot />
  </div>
</template>

// packages/svelte/src/lib/Tabs/List/List.svelte
<script lang="ts">
  import { createClassString } from '@internal/utils';

  let classProp: string = '';
  export { classProp as class };
  export let vertical: boolean = false;
</script>

<div
  class={
    createClassString('a11y-tabs-list', classProp ? classProp : '')
  }
  aria-orientation={vertical ? 'vertical' : 'horizontal'}
  {...$$restProps}
>
  <slot></slot>
</div>
