// packages/svelte/src/App.svelte
<script lang="ts">
  import {
    Accordion,
    Modal,
    Tabs,
  } from './lib'
</script>

<main>
  <Accordion>
    <Accordion.Item>
      <Accordion.Toggle>Title</Accordion.Toggle>
      <Accordion.Content>Content</Accordion.Content>
    </Accordion.Item>
  </Accordion>

  <button aria-controls="modal">
    Modal
  </button>

  <Modal id="modal">
    <Modal.Heading>Title</Modal.Heading>
    <Modal.Content>Content</Modal.Content>
    <button data-modal-close>Cancel</button>
  </Modal>

  <Tabs>
    <Tabs.List>
      <Tabs.Toggle>One</Tabs.Toggle>
      <Tabs.Toggle>Two</Tabs.Toggle>
      <Tabs.Toggle>Three</Tabs.Toggle>
    </Tabs.List>
    <Tabs.Panel>One content</Tabs.Panel>
    <Tabs.Panel>Two content</Tabs.Panel>
    <Tabs.Panel>Three content</Tabs.Panel>
  </Tabs>
</main>

// packages/vue/src/App.vue
<script setup lang="ts">
import { Accordion, Modal, Tabs } from './components';
</script>

<template>
  <Accordion>
    <Accordion.Item>
      <Accordion.Toggle>Title</Accordion.Toggle>
      <Accordion.Content>Content</Accordion.Content>
    </Accordion.Item>
    <Accordion.Item>
      <Accordion.Toggle>Title</Accordion.Toggle>
      <Accordion.Content>Content</Accordion.Content>
    </Accordion.Item>
    <Accordion.Item>
      <Accordion.Toggle>Title</Accordion.Toggle>
      <Accordion.Content>Content</Accordion.Content>
    </Accordion.Item>
  </Accordion>

  <button aria-controls="modal">Modal</button>
  <Modal id="modal">
    <Modal.Heading>Title</Modal.Heading>
    <Modal.Content><button data-modal-close>Cancel</button></Modal.Content>
  </Modal>

  <Tabs>
    <Tabs.List>
      <Tabs.Toggle>One</Tabs.Toggle>
      <Tabs.Toggle>Two</Tabs.Toggle>
      <Tabs.Toggle>Three</Tabs.Toggle>
    </Tabs.List>
    <Tabs.Panel>Content one</Tabs.Panel>
    <Tabs.Panel>Content two</Tabs.Panel>
    <Tabs.Panel>Content three</Tabs.Panel>
  </Tabs>
</template>
