// packages/react/src/components/Modal/Heading/Heading.tsx
import { forwardRef } from 'react';
import { createClassString } from '@shared/utils';

import type {
  PolymorphicComponentPropsWithRef,
  PolymorphicRef,
} from '../../../types';

interface Props {
  className?: string;
}

export type ModalHeadingProps<C extends React.ElementType> =
  PolymorphicComponentPropsWithRef<C, Props>;

export const ModalHeading = forwardRef(
  <C extends React.ElementType = 'h2'>(
    { as, className, ...rest }: ModalHeadingProps<C>,
    ref?: PolymorphicRef<C>,
  ) => {
    const Component = as || 'h2';

    return (
      <Component
        {...rest}
        ref={ref}
        className={createClassString(
          'a11y-modal-heading',
          className ? className : '',
        )}
      />
    );
  },
);

ModalHeading.displayName = 'ModalHeading';

export default ModalHeading;

// packages/svelte/src/lib/Modal/Heading/Heading.svelte
<script lang="ts">
  import { createClassString } from '@shared/utils';

  let classProp: string = '';
  export { classProp as class };
  export let level: 2 | 3 | 4 = 2;

  const classes = createClassString(
    'a11y-modal-heading', classProp ? classProp : ''
  );
</script>

{#if level === 3}
  <h3 class={classes} {...$$restProps}><slot></slot></h3>
{:else if level === 4}
  <h4 class={classes} {...$$restProps}><slot></slot></h4>
{:else}
  <h2 class={classes} {...$$restProps}><slot></slot></h2>
{/if}
