// packages/vue/src/components/Modal/Heading/Heading.vue
<script lang="ts">
import { defineComponent } from 'vue';
import type { PropType } from 'vue';

type Level = 2 | 3 | 4;

export default defineComponent({
  name: 'A11yModalHeading',
  props: {
    level: {
      type: Number as PropType<Level>,
      default: 2,
    },
  }
});
</script>

<template>
  <h3 class="a11y-modal-heading" v-if="level === 3"><slot /></h3>
  <h4 class="a11y-modal-heading" v-else-if="level === 4"><slot /></h4>
  <h2 class="a11y-modal-heading" v-else><slot /></h2>
</template>

// packages/svelte/src/lib/Modal/Heading/Heading.svelte
<script lang="ts">
  import { createClassString } from '@internal/utils';

  let classProp: string = '';
  export { classProp as class };
  export let level: 2 | 3 | 4 = 2;

  const classes = createClassString(
    'a11y-modal-heading', classProp ? classProp : ''
  );
</script>

{#if level === 3}
  <h3 class={classes} {...$$restProps}><slot></slot></h3>
{:else if level === 4}
  <h4 class={classes} {...$$restProps}><slot></slot></h4>
{:else}
  <h2 class={classes} {...$$restProps}><slot></slot></h2>
{/if}
