// packages/svelte/src/lib/Accordion/Item/Item.svelte
<script lang="ts">
  import { createClassString } from '@internal/utils';

  let classProp: string = '';
  export { classProp as class };
  export let expanded: boolean = false;
</script>

<div
  class={
    createClassString(
      'a11y-accordion-item',
      expanded ? 'expanded' : '',
      classProp ? classProp : ''
    )
  }
  {...$$restProps}
>
  <slot></slot>
</div>

// packages/vue/src/components/Accordion/Item/Item.vue
<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'A11yAccordionItem',
  props: {
    expanded: {
      type: Boolean,
      default: false,
    },
  },
});
</script>

<template>
  <div class="a11y-accordion-item" :class="{ expanded: expanded }">
    <slot />
  </div>
</template>
