// packages/vue/src/components/Tabs/List/List.vue
<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'A11yTabsList',
  props: {
    vertical: {
      type: Boolean,
      default: false,
    },
  },
  data(props) {
    const orientation = props?.vertical ? 'vertical' : 'horizontal';

    return {
      orientation,
    };
  },
});
</script>

<template>
  <div class="a11y-tabs-list" :aria-orientation="orientation">
    <slot />
  </div>
</template>

// packages/@spearui-react/src/components/Tabs/List/List.tsx
import { forwardRef } from 'react';

import type {
  PolymorphicComponentPropsWithRef,
  PolymorphicRef,
} from '../../../types';

interface Props {
  children?: React.ReactNode;
  vertical?: boolean;
}

type TabsListProps<C extends React.ElementType> =
  PolymorphicComponentPropsWithRef<C, Props>;

export const TabsList = forwardRef(
  <C extends React.ElementType = 'div'>(
    { as, vertical, ...rest }: TabsListProps<C>,
    ref?: PolymorphicRef<C>,
  ) => {
    const Component = as || 'div';

    return (
      <Component
        {...rest}
        ref={ref}
        data-tabs-list
        aria-orientation={vertical ? 'vertical' : 'horizontal'}
      />
    );
  },
);

TabsList.displayName = 'TabsList';

export default TabsList;
